[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://letter-writer-app-backend.vercel.app"
    Access-Control-Allow-Credentials = "true"